genie/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.i18n import JavaScriptCatalog

from . import settings
from genie_core import views as core_views

urlpatterns = [
    path("", core_views.HomePageView.as_view(), name="home"),
    path("login/", core_views.LoginUserView.as_view(), name="login"),
    path("logout/", core_views.LogoutView.as_view(), name="logout"),
    path("admin/", admin.site.urls),
    path("i18n/", include("django.conf.urls.i18n")),
    path("jsi18n/", JavaScriptCatalog.as_view(), name="javascript-catalog"),
    path("summernote/", include("django_summernote.urls")),
    path("api/", include("genie.api_urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

genie_core/api/urls.py
"""
URL patterns for horilla_core API
"""

from django.urls import include, path
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)

from genie_core.api.views import (
    BusinessHourViewSet,
    CompanyViewSet,
    CustomerRoleViewSet,
    DepartmentViewSet,
    HolidayViewSet,
    HorillaAttachmentViewSet,
    HorillaUserViewSet,
    ImportHistoryViewSet,
    PartnerRoleViewSet,
    RoleViewSet,
    ScoringCriterionViewSet,
    ScoringRuleViewSet,
    TeamRoleViewSet,
)

# Create a router and register our viewsets with it
router = DefaultRouter()
router.register(r"companies", CompanyViewSet)
router.register(r"departments", DepartmentViewSet)
router.register(r"roles", RoleViewSet)
router.register(r"users", HorillaUserViewSet)

router.register(r"business-hours", BusinessHourViewSet)
router.register(r"team-roles", TeamRoleViewSet)
router.register(r"customer-roles", CustomerRoleViewSet)
router.register(r"partner-roles", PartnerRoleViewSet)
router.register(r"scoring-rules", ScoringRuleViewSet)
router.register(r"scoring-criteria", ScoringCriterionViewSet)
router.register(r"import-histories", ImportHistoryViewSet)
router.register(r"attachments", HorillaAttachmentViewSet)
router.register(r"holidays", HolidayViewSet)


# The API URLs are now determined automatically by the router
urlpatterns = [
    # JWT Authentication endpoints
    path("token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    # Include the router URLs
    path("", include(router.urls)),
]

genie_core/urls.py
from django.urls import include, path, re_path

from genie_core.change_password import ChangePasswordFormView, ChangePasswordView
from genie_core.forgot_password import ForgotPasswordView, PasswordResetConfirmView

from . import branches as branches_views
from . import customer_role as customer_role_views
from . import departments as department_views
from . import export_data as export_data_views
from . import fiscal_year as fiscal_year_views
from . import groups_and_permissions as permission_views
from . import import_data, initialiaze_database, load_data
from . import multiple_currency as multiple_currency_views
from . import partner_role as partner_role_views
from . import recycle_bin as recycle_bin_views
from . import regional_formating as regional_formating_views
from . import roles as roles_views
from . import scoring_rule as scoring_rule_views
from . import team_role as team_role_views
from . import user_holidays as user_holidays_views
from . import user_login_history as user_login_history_views
from . import users as user_views
from . import views

app_name = "horilla_core"
urlpatterns = [
    # Include API URLs
    re_path(r"^media/(?P<path>.*)$", views.protected_media, name="protected_media"),
    path("api/", include("genie_core.api.urls")),
    path("", views.HomePageView.as_view(), name="home_view"),
    path("login/", views.LoginUserView.as_view(), name="login"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("active-tab/", views.SaveActiveTabView.as_view(), name="active_tab"),
    path("analytics-track/", views.AnalyticsTrackView.as_view(), name="analytics_track"),
    path("settings-view/", views.SettingView.as_view(), name="settings_view"),
    path("my-settings-view/", views.MySettingView.as_view(), name="my_settings_view"),
    path(
        "company-details-tab/",
        views.CompanyDetailsTab.as_view(),
        name="company_details_tab",
    ),
    path(
        "company-information/",
        views.ConmpanyInformationView.as_view(),
        name="company_information",
    ),
    path(
        "company-tab-view/",
        views.ConmpanyInformationTabView.as_view(),
        name="company_tab_view",
    ),
    path(
        "company-fiscal-year-tab/",
        views.CompanyFiscalYearTab.as_view(),
        name="company_fiscal_year_tab",
    ),
    path(
        "edit-company/<int:pk>/", views.CompanyFormView.as_view(), name="edit_company"
    ),
    path("create-company/", views.CompanyFormView.as_view(), name="create_company"),
    path(
        "switch-company/<int:company_id>/",
        views.SwitchCompanyView.as_view(),
        name="switch_company",
    ),
    # Holiday Urls
    path(
        "holiday-list-view/", views.HolidayListView.as_view(), name="holiday_list_view"
    ),
    path("holiday-view/", views.HolidayView.as_view(), name="holiday_view"),
    path(
        "holiday-create-form/",
        views.HolidayFormView.as_view(),
        name="holiday_create_form",
    ),
    path(
        "holiday-update-form/<int:pk>/",
        views.HolidayFormView.as_view(),
        name="holiday_update_form",
    ),
    path(
        "holiday-delete-view/<int:pk>/",
        views.HolidayDeleteView.as_view(),
        name="holiday_delete_view",
    ),
    path(
        "holiday-detail-view/<int:pk>/",
        views.HolidayDetailView.as_view(),
        name="holiday_detail_view",
    ),
    # Fiscal Year Urls
    path(
        "fiscal-year-form/",
        fiscal_year_views.FiscalYearFormView.as_view(),
        name="fiscal_year_form",
    ),
    path(
        "fiscal-year-form/<int:pk>/",
        fiscal_year_views.FiscalYearFormView.as_view(),
        name="fiscal_year_form_edit",
    ),
    path(
        "fiscal-year-fields/",
        fiscal_year_views.FiscalYearFieldsView.as_view(),
        name="fiscal_year_fields",
    ),
    path(
        "fiscal-year-calendar-preview/",
        fiscal_year_views.FiscalYearCalendarPreviewView.as_view(),
        name="fiscal_year_calendar_preview",
    ),
    path(
        "fiscal-year-calendar/<int:pk>/",
        fiscal_year_views.FiscalYearCalendarView.as_view(),
        name="fiscal_year_calendar",
    ),
    path(
        "calculate-week-start-day/",
        fiscal_year_views.CalculateWeekStartDayView.as_view(),
        name="calculate_week_start_day",
    ),
    # Multiple Currency Urls
    path(
        "multiple-currency/",
        views.CompanyMultipleCurrency.as_view(),
        name="multiple_currency",
    ),
    path(
        "currency-list-view/",
        multiple_currency_views.CurrencyListView.as_view(),
        name="currency_list_view",
    ),
    path(
        "change-default-currency/<int:pk>/",
        multiple_currency_views.ChangeDefaultCurrencyView.as_view(),
        name="change_default_currency",
    ),
    path(
        "add-currency/",
        multiple_currency_views.AddCurrencyView.as_view(),
        name="add_currency",
    ),
    path(
        "edit-currency/<int:pk>/",
        multiple_currency_views.AddCurrencyView.as_view(),
        name="edit_currency",
    ),
    path(
        "change-default-currency-form/",
        multiple_currency_views.ChangeDefaultCurrencyFormView.as_view(),
        name="change_default_currency_view",
    ),
    path(
        "change-conversion-rate-view/",
        multiple_currency_views.ConversionRateFormView.as_view(),
        name="conversion_rate_view",
    ),
    path(
        "dated-conversion-rates/",
        multiple_currency_views.DatedConversionRateFormView.as_view(),
        name="dated_conversion_rate_view",
    ),
    path(
        "dated-currency-list-view/",
        multiple_currency_views.DatedCurrencyListView.as_view(),
        name="dated_currency_list_view",
    ),
    path(
        "delete-currency/<int:pk>/",
        multiple_currency_views.CurrencyDeleteView.as_view(),
        name="delete_currency",
    ),
    # Business Hour urls
    path(
        "business-hour-view/",
        views.BusinessHourView.as_view(),
        name="business_hour_view",
    ),
    path(
        "business-hour-list-view/",
        views.BusinessHourListView.as_view(),
        name="business_hour_list_view",
    ),
    path(
        "business-hour-create-form/",
        views.BusinessHourFormView.as_view(),
        name="business_hour_create_form",
    ),
    path(
        "business-hour-update-form/<int:pk>/",
        views.BusinessHourFormView.as_view(),
        name="business_hour_update_form",
    ),
    path(
        "business-hour-delete-view/<int:pk>/",
        views.BusinessHourDeleteView.as_view(),
        name="business_hour_delete_view",
    ),
    path(
        "business-hour-detail-view/<int:pk>/",
        views.BusinessHourDetailView.as_view(),
        name="business_hour_detail_view",
    ),
    # User urls
    path("user-view/", user_views.UserView.as_view(), name="user_view"),
    path("user-nav-view/", user_views.UserNavbar.as_view(), name="user_nav_view"),
    path("user-list-view/", user_views.UserListView.as_view(), name="user_list_view"),
    path(
        "user-kanban-view/",
        user_views.UserKanbanView.as_view(),
        name="user_kanban_view",
    ),
    path(
        "user-create-form/", user_views.UserFormView.as_view(), name="user_create_form"
    ),
    path(
        "user-edit-form/<int:pk>/",
        user_views.UserFormView.as_view(),
        name="user_edit_form",
    ),
    path(
        "user-delete-view/<int:pk>/",
        user_views.UserDeleteView.as_view(),
        name="user_delete_view",
    ),
    path(
        "user-detail-view/<int:pk>/",
        user_views.UserDetailView.as_view(),
        name="user_detail_view",
    ),
    path(
        "my-profile-view/",
        user_views.MyProfileView.as_view(),
        name="my_profile_view",
    ),
    path(
        "login-history-list/",
        user_views.LoginHistoryListView.as_view(),
        name="login_history_list",
    ),
    path(
        "login-history-navbar/",
        user_views.LoginHistoryNavbar.as_view(),
        name="login_history_navbar",
    ),
    path(
        "login-history-view/",
        user_views.LoginHistoryView.as_view(),
        name="login_history_view",
    ),
    path(
        "get-country-subdivisions/",
        views.GetCountrySubdivisionsView.as_view(),
        name="get_country_subdivisions",
    ),
    # role urls
    path("roles-view/", views.RolesView.as_view(), name="roles_view"),
    path("create-roles-view/", roles_views.AddRole.as_view(), name="create_roles_view"),
    path(
        "edit-roles-view/<int:pk>/",
        roles_views.AddRole.as_view(),
        name="edit_roles_view",
    ),
    path(
        "add-user-to-roles-view/",
        roles_views.AddUserToRole.as_view(),
        name="add_user_to_roles_view",
    ),
    path(
        "delete-user-from-role/<int:pk>/",
        roles_views.DeleteUserFromRole.as_view(),
        name="delete_user_from_role",
    ),
    path(
        "delete-role/<int:pk>/",
        roles_views.RoleDeleteView.as_view(),
        name="delete_role",
    ),
    path(
        "view-user-in-role/",
        roles_views.UsersInRoleView.as_view(),
        name="view_user_in_role",
    ),
    path(
        "view-user-in-role-list-view/",
        roles_views.RoleUsersListView.as_view(),
        name="view_user_in_role_list_view",
    ),
    path(
        "view-user-in-role-nav-view/",
        roles_views.RoleUsersNavView.as_view(),
        name="view_user_in_role_nav_view",
    ),
    # path('edit-roles-view/<int:pk>/',roles_views.AddRole.as_view(),name="edit_roles_view"),
    # branches urls
    path("branches-view/", branches_views.BranchesView.as_view(), name="branches_view"),
    path(
        "branches-nav-view/",
        branches_views.BranchNavbar.as_view(),
        name="branches_nav_view",
    ),
    path(
        "branches-list-view/",
        branches_views.BranchListView.as_view(),
        name="branches_list_view",
    ),
    path(
        "branch-detail-view/<int:pk>/",

genie_generics/urls.py
from django.urls import path

from genie_generics import horilla_support_views as view
from genie_generics.global_search import GlobalSearchView

from . import views

app_name = "horilla_generics"

urlpatterns = [
    path(
        "update-kanban-item/<str:app_label>/<str:model_name>/",
        views.HorillaKanbanView.as_view(),
        name="update_kanban_item",
    ),
    path(
        "update-kanban-column-order/<str:app_label>/<str:model_name>/",
        views.HorillaKanbanView.as_view(),
        name="update_kanban_column_order",
    ),
    path(
        "kanban-load-more/<str:app_label>/<str:model_name>/",
        view.KanbanLoadMoreView.as_view(),
        name="kanban_load_more",
    ),
    path(
        "create-kanban-group/",
        view.HorillaKanbanGroupByView.as_view(),
        name="create_kanban_group",
    ),
    path(
        "column-selector/",
        view.ListColumnSelectFormView.as_view(),
        name="column_selector",
    ),
    path("move-field/", view.MoveFieldView.as_view(), name="move_field"),
    path(
        "save-filter-list/", view.SaveFilterListView.as_view(), name="save_filter_list"
    ),
    path("pin-view/", view.PinView.as_view(), name="pin_view"),
    path(
        "delete-saved-list/",
        view.DeleteSavedListView.as_view(),
        name="delete_saved_list",
    ),
    path(
        "update-pipeline/<int:pk>/",
        views.HorillaDetailView.as_view(),
        name="update_pipeline",
    ),
    path(
        "edit/<int:pk>/<str:field_name>/<str:app_label>/<str:model_name>/",
        view.EditFieldView.as_view(),
        name="edit_field",
    ),
    path(
        "cancel/<int:pk>/<str:field_name>/<str:app_label>/<str:model_name>/",
        view.CancelEditView.as_view(),
        name="cancel_edit",
    ),
    path(
        "update/<int:pk>/<str:field_name>/<str:app_label>/<str:model_name>/",
        view.UpdateFieldView.as_view(),
        name="update_field",
    ),
    path(
        "dynamic-create/<str:app_label>/<str:model_name>/",
        views.HorillaDynamicCreateView.as_view(),
        name="dynamic_create",
    ),
    path(
        "related-list-content/<int:pk>/",
        views.HorillaRelatedListContentView.as_view(),
        name="related_list_content",
    ),
    path(
        "<str:app_label>/<str:model_name>/select2/",
        view.HorillaSelect2DataView.as_view(),
        name="model_select2",
    ),
    path("search/", GlobalSearchView.as_view(), name="global_search"),
    path(
        "remove-condition-row/<str:row_id>/",
        view.RemoveConditionRowView.as_view(),
        name="remove_condition_row",
    ),
    path(
        "get-field-value-widget/",
        view.GetFieldValueWidgetView.as_view(),
        name="get_field_value_widget",
    ),
    path(
        "notes-attachment-create/",
        views.HorillaNotesAttachmentCreateView.as_view(),
        name="notes_attachment_create",
    ),
    path(
        "notes-attachment-edit/<int:pk>/",
        views.HorillaNotesAttachmentCreateView.as_view(),
        name="notes_attachment_edit",
    ),
    path(
        "notes-attachment-view/<int:pk>/",
        views.HorillaNotesAttachementDetailView.as_view(),
        name="notes_attachment_view",
    ),
    path(
        "notes-attachment-delete/<int:pk>/",
        views.HorillaNotesAttachmentDeleteView.as_view(),
        name="notes_attachment_delete",
    ),
]

genie_core/templates/permissions/assign_perm_form.html
{% load i18n %}
<div id="assign-users-modal">
    <div class="flex justify-between items-center p-4 ">
        <h2 class="text-lg font-semibold text-gray-900">{% trans "Assign Users" %}</h2>
        <button type="button" class="text-gray-400 hover:text-gray-600" onclick="closeContentModal()">
            <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
            </svg>
        </button>
    </div>

    <form method="post" action="{% url 'horilla_core:assign_users_perm' %}" hx-post="{% url 'horilla_core:assign_users_perm' %}" hx-target="#assign-users-modal" hx-swap="outerHTML">
        {% csrf_token %}
        <input type="hidden" id="selected-user-ids" name="selected_user_ids" value="">
        <div class="p-4 space-y-4">
            <div class="space-y-2">
                <label class="block text-sm font-medium text-gray-700">{% trans "Users" %}</label>
                <select name="users"
                    id="selected-users"
                    multiple
                    class="select2-pagination w-full text-sm"
                    data-url="{% url 'horilla_generics:model_select2' app_label='horilla_core' model_name='HorillaUser' %}?is_superuser=false"
                    data-placeholder="{% trans 'Select users' %}"
                    onchange="updateSelectedUserIds()">
                </select>
            </div>
            <div class="space-y-3 max-h-64 overflow-y-auto">
                <div class="bg-primary-300 px-4 py-3">
                    <div class="flex gap-4 items-center justify-between">
                        <div class="flex items-center">
                            <input
                                type="text"
                                class="text-color-600 px-2 py-1.5 pr-[40px] pw-full border border-dark-50 rounded-md focus-visible:outline-0 placeholder:text-[#d3d3d3] placeholder:text-xs text-sm [transition:.3s] focus:border-primary-600"
                                placeholder="{% trans 'Search models...' %}"
                                hx-get="{% url 'horilla_core:search_assign_models' %}"
                                hx-trigger="input changed delay:500ms"
                                hx-target="#assign-model-container"
                                hx-swap="innerHTML"
                                name="search"
                            />
                        </div>

                        <label class="flex items-center text-sm font-semibold text-primary-600">
                            <input
                                type="checkbox"
                                id="master-select-all-user"
                                class="bulk-model-select-all w-4 h-4 border border-[#cfcfcf] rounded-sm accent-[#e54f38] mr-2"
                                {% if master_select_all_checked %}checked{% endif %}
                                hx-post="{% url 'horilla_core:bulk_update_user_all_permissions' %}"
                                hx-trigger="change"
                                hx-vals='js:{"checked": event.target.checked, "users": getBulkSelectedUsers()}'
                                hx-on::after-request="$('#reloadMessagesButton').click();toggleAllBulkChecked(this)"
                                hx-swap="none"
                            />
                            {% trans "Select All" %}
                        </label>
                    </div>
                </div>
                <div id="assign-model-container">
                    {% for model in all_models %}
                        <div class="border-[1px] border-[solid] border-[#efefef] last:border-b-0 px-4 py-2">
                            <div class="flex gap-2 bulk-permItem">
                                <div class="flex items-center">
                                    <label class="flex items-center">
                                        <input
                                            type="checkbox"
                                            class="bulk-model-select-all w-4 h-4 bg-[#E9EDF7] rounded-sm accent-[#e54f38] mr-2"
                                            {% if model.select_all_checked %}checked{% endif %}
                                            hx-post="{% url 'horilla_core:bulk_update_user_model_permissions'%}"
                                            hx-trigger="change"
                                            hx-vals='js:{"model_name": "{{ model.model_name }}", "app_label": "{{ model.app_label }}", "checked": event.target.checked}'
                                            hx-on::after-request="$('#reloadMessagesButton').click();toggleBulkChecked($(this));"
                                            hx-swap="none"
                                        />
                                    </label>
                                </div>
                                <div class="w-36 text-sm">
                                    {% if model.is_managed %}
                                        <button
                                            type="button"
                                            class="whitespace-nowrap text-left hover:text-primary-600"
                                            hx-get="{% url 'horilla_core:model_fields_modal_bulk' model.app_label model.model_name %}?context=bulk"
                                            hx-vals='js:{"selected_user_ids": getSelectedUserIds()}'
                                            hx-target="#modalBox"
                                            hx-swap="innerHTML"
                                            onclick="openModal()"
                                        >
                                            {{ model.verbose_name }}
                                        </button>
                                    {% else %}
                                        <div class="relative group inline-block cursor-pointer">
                                            <span class="whitespace-nowrap text-gray-400 ">
                                                {{ model.verbose_name }}
                                            </span>
                                            <span class="min-w-max z-40 absolute h-auto py-[3px] px-[15px] left-[40px] top-0 bg-[#000000] text-[.7rem] rounded-[5px] text-white opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none">
                                                {% trans 'Field permissions not available for this model' %}
                                            </span>
                                        </div>
                                    {% endif %}
                                </div>
                                <div class="flex gap-5 text-xs text-dark-300">
                                    {% for perm in model.permissions %}
                                        <label class="flex items-center whitespace-nowrap">
                                            <input
                                                type="checkbox"
                                                name="permissions"
                                                value="{{ perm.id }}"
                                                class="bulk-individual-perm w-4 h-4 border border-[#cfcfcf] rounded-sm accent-[#e54f38] mr-2"
                                                {% if perm.has_perm %}checked{% endif %}
                                                />
                                            {{ perm.label }}
                                        </label>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>

            {% if form.errors %}
                <div class="bg-red-50 border border-red-200 rounded-md p-3">
                    {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                            <p class="text-sm text-red-600">{{ error }}</p>
                        {% endfor %}
                    {% endfor %}
                </div>
            {% endif %}
        </div>

        <div class="flex justify-end gap-2 p-4 bg-gray-50">
            <div class="flex justify-end p-5 pt-0">
                <button type="submit" class="text-sm px-4 py-2 bg-primary-600 rounded-md hover:bg-primary-800 transition duration-300 text-[white]">
                    {% trans "Save" %}
                </button>
            </div>
        </div>
    </form>
</div>
<script>
    function getBulkSelectedUsers() {
        var users = [];
        $('#selected-users option:selected').each(function() {
            users.push($(this).val());
        });
        return users;
    }

    function updateSelectedUserIds() {
        var users = getBulkSelectedUsers();
        $('#selected-user-ids').val(users.join(','));
        console.log('Updated selected user IDs:', users.join(','));
    }

    function getSelectedUserIds() {
        updateSelectedUserIds();
        return $('#selected-user-ids').val();
    }

    function toggleBulkChecked($elm) {
        var is_checked = $elm.is(':checked');
        $elm.closest('.bulk-permItem').find('.bulk-individual-perm').prop('checked', is_checked);
    }

    function toggleAllBulkChecked(el) {
        var $elm = $(el);
        var is_checked = $elm.is(':checked');

        $('.bulk-model-select-all, .bulk-individual-perm').prop('checked', is_checked);
    }

    $(document).ready(function() {
        $('#selected-users').on('select2:select select2:unselect', function() {
            updateSelectedUserIds();
        });

        setTimeout(updateSelectedUserIds, 500);
    });
</script>

genie_core/templates/permissions/group.html
{% load i18n %}
<div class="mb-5 p-3 bg-yellow-50 border border-[#f3edb0] rounded-lg">
    <p class="text-xs text-yellow-800">
      <strong>{% trans "Note:" %}</strong> {% trans "To manage field-level permissions, simply click the name of a model." %}
    </p>
</div>
<div class="" id="group-container" role="tabpanel" aria-labelledby="details-tab">
    <button id="reloadButton" hidden hx-get="{{ request.path }}?{{request.GET.urlencode}}" hx-target="#group-container" hx-swap="outerHTML" hx-select="#group-container">click</button>
    <div id="messages-container" style="display: none;">
        {% for message in messages %}
            <div class="message" data-level="{{ message.tags }}" data-message="{{ message }}"></div>
        {% endfor %}
    </div>

    <h3 class="text-md font-semibold mb-3">{% trans "User Groups" %}</h3>
    <div class="flex gap-3 ">
        <div class="w-[250px]">
            <button class="mb-2 text-sm px-2 py-2 flex gap-2 pt-1 items-center text-primary-600"
                hx-get="{% url 'horilla_core:create_roles_view' %}"
                hx-target="#modalBox"
                hx-swap="innerHTML"
                onclick="openModal()">
                {% trans "Add Groups" %}
                <i class="fa-solid fa-plus text-xs"></i>
            </button>
            <div class="custom-scroll max-h-80 overflow-y-auto border-[1px] border-primary-400 p-3 bg-white rounded-md">
                <ul id="custom-tabs" class="flex flex-col space-y-1 text-sm font-normal text-gray-500 dark:text-gray-400 h-full ">
                    {% for role in roles %}
                        <li class="mb-0">
                            <a href="#"
                                data-role-id="{{ role.id }}"
                                hx-get="{% url 'horilla_core:role_permissions_view' role.id %}"
                                hx-target="#tab-contents"
                                hx-swap="innerHTML"
                                class="role-tab items-center px-5 py-2 rounded-md w-full flex gap-3 transition
                                {% if forloop.first %}
                                    bg-primary-600 text-white
                                {% else %}
                                    bg-transparent text-gray-800
                                {% endif %}">
                                <div class="flex justify-between w-full">
                                    <div class="flex gap-2 items-center">
                                        {{ role.role_name }}
                                    </div>
                                    <span class="bg-white text-primary-600 w-6 h-6 font-semibold rounded-full flex items-center justify-center">
                                        {{ role.users.count }}
                                    </span>
                                </div>
                            </a>
                        </li>
                    {% endfor %}
                </ul>

            </div>

        </div>

        <div id="group-content" class="w-[calc(_100%_-_250px_)] pe-2">
            <div class="custom-scroll overflow-hidden overflow-x-auto">
                <div id="tab-contents">
                </div>
            </div>



        </div>
    </div>

    <script>
        $(document).ready(function () {
            const tabButtons = document.querySelectorAll(".role-tab");

            tabButtons.forEach((btn) => {
                btn.addEventListener("click", (e) => {
                    e.preventDefault();

                    tabButtons.forEach((b) => {
                        b.classList.remove("bg-primary-600", "text-white");
                        b.classList.add("bg-transparent", "text-gray-800");
                    });

                    btn.classList.remove("bg-transparent", "text-gray-800");
                    btn.classList.add("bg-primary-600", "text-white");

                    localStorage.setItem("rolePermissionSidebar", $(btn).attr("data-role-id"))

                });
            });

            let activeSidemenu = localStorage.getItem("rolePermissionSidebar");
            let activeTab = null;

            if (activeSidemenu) {
                let activeTab = $(`[data-role-id='${activeSidemenu}']`)[0];
            }

            if (!activeTab && tabButtons.length > 0) {
                activeTab = tabButtons[0];
            }

            if (activeTab) {
                tabButtons.forEach((b) => {
                    b.classList.remove("bg-primary-600", "text-white");
                    b.classList.add("bg-transparent", "text-gray-800");
                });

                activeTab.classList.remove("bg-transparent", "text-gray-800");
                activeTab.classList.add("bg-primary-600", "text-white");

                htmx.ajax('GET', activeTab.getAttribute('hx-get'), {
                    target: '#tab-contents',
                    swap: 'innerHTML'
                });
                localStorage.setItem("rolePermissionSidebar", activeTab.getAttribute("data-role-id"));
            }
        });

    </script>
</div>

genie_core/templates/permissions/role_members.html
{% load i18n %}
<button class="text-primary-600 hover:text-primary-800 text-sm flex items-center gap-2 pb-3"
    hx-get="{% url 'horilla_core:add_user_to_roles_view' %}"
    hx-vals='{"role_id": {{ role.id }}}'
    hx-target="#modalBox"
    hx-swap="innerHTML"
    hx-on:click="openModal()">
    <i class="fa-solid fa-plus text-xs">
    </i>
    {% trans "Add Member" %}
</button>
<div id="tab-fu-closed" class="fu-tab-content text-[.8rem] border border-primary-300 rounded-md bg-white">
        {% include "list_view.html" %}
    </div>
</div>